### ISSUE TITLE
any android/windows client that works ?

### ISSUE THREAD

**Issue by kiai72** [FD-/RPiPlay#15]
hello,

don't have a iOS device. I would like to mirror my android device and windows PC.

but everything i try on android brings a "connection error" (for example https://play.google.com/store/apps/details?id=com.splashtop.m360.tx&hl=en)

on windows i tried 5kplayer. But the 5kplayer does not even find the RPiPlay.

So it there any android/windows program you know of, that works with RPiPlay ?

or is the problem related to the waring i get, when i start:
pi@raspberrypi:~/RPiPlay/build $ ./rpiplay -d
> stream info: channel = 2      sample_rate = 44100     frame_size = 480       aot = 39 bitrate = 0
Initialized server socket(s)
*** WARNING *** The program 'rpiplay' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>

**Comment by FD-** [comment]
It's pretty clear why third-party AirPlay clients don't work: These clients implement the least complex, best documented version of the AirPlay mirroring protocol, which is the ancient pre-iOS9 implementation. Since AppleTVs have kept compatibility with ancient iOS versions, that's a viable solution in general.

However, RPiPlay only supports the newer iOS9+ AirPlay mirroring protocol. There are no plans to tackle the tedious task of adding support for that ancient protocol to RPiPlay, just to support a handful of devices that still run these ancient iOS versions and third-party clients.

Actually, it's a pretty stupid idea to connect two open platforms (Android and Raspberry Pi) via a proprietary complex protocol such as AirPlay anyway. There must be better solutions (I think some Miracast software exists for the Raspberry Pi), and if there isn't, a new solution should be relatively easy to build without all the encryption stuff that AirPlay involves.
