### ISSUE TITLE
RPiPlay doesn't show in Screen Mirroring on iOS 13.1.1

### ISSUE THREAD

**Issue by altrem** [FD-/RPiPlay#26]
Hello,

I've built RPiPlay with the recommended cmake flags in your README and started it. It works pretty well on my MBP with macOS Mojave, but my iPhone XS with the latest iOS version (13.1.1) doesn't find any screen mirroring target (I go through the Control Center).

Is there any known issue on that version of iOS? 
My launch command is : `rpiplay -a hdmi` and it's plugged to a TV.
They're on the same wifi network as well.

Thanks!

**Comment by FD-** [comment]
Well, the most likely reason is that the two devices are _not_ on the same network. You could run a Bonjour scanner on your iPhone and check if you see RPiPlay there. If RPiPlay is visible there, but still not picked up by the iPhone, you could try a device reboot. Otherwise, rebooting the Pi might also help.
