### ISSUE TITLE
Update for bullseye?

### ISSUE THREAD

**Issue by fivenote** [FD-/RPiPlay#304]
Will there be some updates for Raspian bullseye?

Bullseye doesn’t have gstreamer out of the box. What packages does rpiplay need?

Also, getting this when running rpiplay…

```
rpiplay: error while loading shared libraries: libbrcmGLESv2.so: cannot open shared object file: No such file or directory
```

Thanks for any help to get running on bullseye.

**Comment by pallas** [comment]
This does run on Bullseye, I've been doing it for months.

You always needed to install gstreamer if you want to use that, see https://github.com/FD-/RPiPlay/issues/294#issuecomment-974752584 but note that this is literally in the README.

If you want to use OpenMAX, you have to reinstall it via rpi-update, as per https://github.com/FD-/RPiPlay/issues/296#issuecomment-981210609 but READ the documentation for rpi-update since it can be a dangerous operation and I'm not taking responsibility for bricked hardware.

The above also describes how to correct the shared library issue, with a hat tip to https://raspberrypi.stackexchange.com/a/133496
