### ISSUE TITLE
History/authorship: dsafa22 -> DroidFang?

### ISSUE THREAD

**Issue by fduncanh** [FD-/RPiPlay#314]
Looking through the history of the mirror code,  as documented in the interesting write-up https://www.itread01.com/hkeyxif.html, (which translates well* with Google Chrome and is apparently guided by analysis of [this](https://aapks.com/apk/happycast/version/35810679/dl/))  plus the history in https://github.com/KqSMea8/AirplayServer , it look like the true author of the AirPlay2 mirror code (based on the audio code in shairplay) was "DroidFang", and dsafa22 merely created the github repository for DroidFang   (unless they are one and the same)

* except that getting "millet root" is a mistranslation of getting root in a "xiaomei" device (I guess an android tv box)

**Comment by fduncanh** [comment]
Looks like dsafa22 and droidfang are the same person. (?)

 dsafa22 kept on developing AirplayServer  after the fork to RPiPlay.

latest I saw is dsafa22  commit history up to 2019-08-28 in preserved at https://github.com/jiangban/AirplayServer

**Comment by FD-** [comment]
Yes, back when I started RPiPlay, dsafa22 was still actively working on their branch. Then one day the original dsafa22/AirplayServer including all recent commits disappeared and was replaced by the current one.

**Comment by Artoria2e5** [comment]
The two repo links at the end does seem to agree with the same person assessment. We *could* actually just message dsafa22 on the QQ mail number in those commits to be sure.

An interesting thing to note is that the link seems to be the result of some content farm taking a zh-Hans-CN article and turning it into zh-Hant-TW. https://blog.csdn.net/xqhrs232/article/details/104299336 has a link to an article with an identical but Simplified Chinese name, but that link is dead due to "waiting for moderator approval" shenanigans. Meh.

**Comment by fduncanh** [comment]
A while back I fixed up the translation of what I think is the mirror code author's  (dsafa22 / droid fang?)  article about how he did it.

Its on the UxPlay Wiki https://github.com/FDH2/UxPlay/wiki/AirPlay2

I also found  the Android app he analyzed : com.hpplay.happyplay 7.1.0 APK
